defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  password:
  min_messages: warning

development:
  <<: *defaults
  database: sample_development

test:
  <<: *defaults
  database: sample_test

production:
  <<: *defaults
  database: sample_production
