# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7d228abdd8b8f3bab399559e125c403806d9024926d2eb5de2d601b1eda9b67c1ffe1353ad48d5ab1207c6c7d056f1c948652ec441a26f7f097cb27e5606729

test:
  secret_key_base: 56ac4fa64bb4eafdbb1fd9639d8b0f192a215aeaa57c5da05602098d4e2220833ab07dea42debdf055a6caa688dafcac6e8e315b79c30317f84b1a576e2896a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
